# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@stable'
    'frameworks/kconfig': '@stable'
    'frameworks/ki18n': '@stable'

- 'on': ['Linux', 'FreeBSD', 'macOS', 'Windows']
  'require':
    'frameworks/kxmlgui': '@stable'
    'frameworks/kwidgetaddons': '@stable'
    'frameworks/kcoreaddons': '@stable'
    'frameworks/kconfigwidgets': '@stable'
    'frameworks/kcrash': '@stable'
    'frameworks/kdoctools': '@stable'
    'frameworks/kcompletion': '@stable'
    'frameworks/kdbusaddons': '@stable'
    'frameworks/kio': '@stable'
    'games/libkdegames': '@same'
Options:
  require-passing-tests-on: [ 'Linux', 'FreeBSD']
